version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: taskmanager_db
        POSTGRES_PASSWORD: paswordtest
        POSTGRES_USER: postgres
    ports:
      - "5433:5433"
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db